/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 d:\Aduhh\public\model.glb -o d:\Aduhh\src\components\Model.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'mixamo.com'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    node_0: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Materialmat: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.ComponentPropsWithoutRef<'group'>) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/model.glb')
  const clone = React.useMemo(() => (scene ? SkeletonUtils.clone(scene) : null), [scene])
  const { nodes, materials } = useGraph(clone || scene) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    if (actions['mixamo.com']) {
      actions['mixamo.com'].reset().fadeIn(0.24).play()
    }
  }, [actions])

  if (!nodes || !nodes.mixamorigHips) {
    return null
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="node_0"
            geometry={nodes.node_0.geometry}
            material={materials.Materialmat}
            skeleton={nodes.node_0.skeleton}
            frustumCulled={false}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
